name: Code Analysis
on: [pull_request]
jobs:
  Code-Analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

    #   - name: Install CUDA Toolkit
    #     uses: Jimver/cuda-toolkit@v0.2.14
    #     with:
    #       method: network
    #       use-github-cache: false
    #       use-local-cache: false

      - name: Code Analysis
        uses: JacobDomagala/StaticAnalysis@master
        with:
            comment_title: Code Analysis Results
            cppcheck_args: --enable=warning
            report_pr_changes_only: false
            use_cmake: true
            cmake_args: -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        -DCMAKE_BUILD_TYPE=Debug \
                        -DBUILD_ALL_DEP=ON \
                        -DCHECK_GPU=OFF \
                        -DUSE_CUDA=OFF \
                        -DUSE_OPENCL=OFF \
                        -DUSE_SSE=ON \
                        -DUSE_OPENMP=ON \
                        -DBUILD_TESTING=OFF \
                        -DWITH_COVERAGE=OFF \
                        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON