name: Code Analysis
on: [pull_request]
jobs:
  Code-Analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install cppcheck -y
          pip3 install --upgrade setuptools urllib3 chardet pyOpenSSL pygithub

      # - name: Install CUDA Toolkit
      #   uses: Jimver/cuda-toolkit@v0.2.14
      #   with:
      #     method: network
      #     use-github-cache: false
      #     use-local-cache: false

      - name: Configure NiftyReg
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_CXX_COMPILER=g++ \
                -DCMAKE_BUILD_TYPE=Debug \
                -DBUILD_ALL_DEP=ON \
                -DCHECK_GPU=OFF \
                -DUSE_CUDA=OFF \
                -DUSE_OPENCL=OFF \
                -DUSE_SSE=ON \
                -DUSE_OPENMP=ON \
                -DBUILD_TESTING=OFF \
                -DWITH_COVERAGE=OFF \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                ..

      - name: Code Analysis
        env:
            COMMENT_TITLE: Code Analysis Results
            PR_NUMBER: ${{ github.event.pull_request.number }}
            REPORT_PR_CHANGES_ONLY: false
            GITHUB_TOKEN: ${{ github.token }}
        run: |
            cppcheck -j4 --enable=warning --project=build/compile_commands.json --output-file=analysis.txt
            python3 ${{ github.workspace }}/.github/code_analysis.py -cc analysis.txt -o false -fk false